# Numpy Python Library
NumPy (short for Numerical Python ) is one of the most fundamental libraries in Python for `scientific computing`. It provides support for large, multi-dimensional arrays and matrices along with a collection of mathematical functions to operate on arrays.

At its core it introduces the ndarray (n-dimensional array) object which allows us to `store and manipulate` large datasets in a memory-efficient manner. Unlike Python's built-in lists, NumPy arrays are homogeneous and enable faster operations.

# Important Facts to Know :

1. Vectorized Operations: NumPy operations are faster than Python lists because they use optimized C-based functions.

2. Broadcasting Feature: NumPy allows operations between arrays of different shapes without explicit looping known as broadcasting making it  easier to handle large datasets.

# What is NumPy Used for?

1. With NumPy, you can perform a wide range of numerical operations, including:
2. Creating and manipulating arrays.
3. Performing element-wise and matrix operations.
4. Generating random numbers and statistical calculations.
5. Conducting linear algebra operations.
6. Working with Fourier transformations.
7. Handling missing values efficiently in datasets.

# Why Learn NumPy?

1. NumPy speeds up math operations like addition and multiplication on large groups of numbers compared to regular Python..
2. It’s good for handling large lists of numbers (arrays), so you don’t have to write complicated loops.
3. It gives ready-to-use functions for statistics, algebra and random numbers.
4. Libraries like Pandas, SciPy, TensorFlow and many others are built on top of NumPy.
5. NumPy uses less memory and stores data more efficiently, which matters when working with lots of data.

# Key Features of NumPy
NumPy has various features that make it popular over lists.

1. N-Dimensional Arrays: NumPy's core feature is ndarray, a powerful N-dimensional array object that supports homogeneous data types.
2. Arrays with High Performance: Arrays are stored in contiguous memory locations, enabling faster computations than Python lists.
3. Broadcasting: This allows element-wise computations between arrays of different shapes. It simplifies operations on arrays of various shapes by automatically aligning their dimensions without creating new data.
4. Vectorization: Eliminates the need for explicit Python loops by applying operations directly on entire arrays.
5. Linear algebra: NumPy contains routines for linear algebra operations, such as matrix multiplication, decompositions, and determinants.

# Creating NumPy Arrays
Using ndarray : The array object is called ndarray. NumPy arrays are created using the array() function.

In [1]:
import numpy as np

# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Using Numpy Functions: 
NumPy provides convenient methods to create arrays initialized with specific values like zeros and ones:

In [2]:
import numpy as np

a1_zeros = np.zeros((3, 3))
a2_ones = np.ones((2, 2))
a3_range = np.arange(0, 10, 2)

print(a1_zeros)
print(a2_ones)
print(a3_range)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


# NumPy Array Indexing
Knowing the basics of NumPy array indexing is important for analyzing and manipulating the array object.

Basic Indexing: Basic indexing in NumPy allows you to access elements of an array using indices.
Example:

In [3]:
import numpy as np

# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr1d[2])  

# Negative indexing
print("Negative indexing:", arr1d[-1])  

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Multidimensional array access
print("Multidimensional array access:", arr2d[1, 0])

Single element access: 30
Negative indexing: 50
Multidimensional array access: 4


# Slicing: 
Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr[:, 1])

Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]
